return {
  require 'vinvit.plugins.gitsigns',
  require 'vinvit.plugins.which-key',
  require 'vinvit.plugins.telescope',
  require 'vinvit.plugins.lsp',
  require 'vinvit.plugins.conform',
  require 'vinvit.plugins.blink',
  require 'vinvit.plugins.treesitter',
  require 'vinvit.plugins.todo-comments',
  require 'vinvit.plugins.mini',
  require 'vinvit.plugins.nvim-tmux-navigator',
  require 'vinvit.plugins.transparent',
  require 'vinvit.plugins.catppuccin',
  require 'vinvit.plugins.rust',
  require 'vinvit.plugins.lazygit',
}
